# Generated by Django 4.2.6 on 2023-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'open'), ('progress', 'progress'), ('pending', 'pending'), ('done', 'done')], default='open', max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(choices=[('high', 3), ('medium', 2), ('low', 1)], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
